### ISSUE TITLE
JCGS reviewer 1: (3) acknowledge the limitation

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/lineup_residual_diagnostics#13]
Reviewer 1: "All your examples are simulated data and very obviously so. Real data shows much greater irregularity - the points will usually not be uniformly spaced along the x-axis. The response may be somewhat discrete or have other features that will distinguish it from bland randomness. This would seem to offer greater challenges to your lineup idea as generating data under the null will be much more challenging. If we simulate from the null model, the real data will be very obvious. You have done an experiment but the reality would be more like an observational study. This limits the scope of your conclusions which you should clearly acknowledge."

**Comment by TengMCing** [comment]
Real data indeed shows much greater irregularity and the data points will usually not be uniformly spaced along the x-axis. However, we have already considered some possibilities by setting the response distribution as discrete, normal or skewed. The reviewer may have missed that part. 

Furthermore, the irregular response distribution will not make drawing null plots more difficult. We follow the standard procedure to generate null data, which only assumes the model is correctly specified under the null hypothesis.

"If we simulate from the null model, the real data will be very obvious. (given the response distribution is irregular?)". I don't agree with this statement. The real data will not be obvious only because of the irregular response distribution. The misspecified patterns still need to be strong enough to be recognised.   

It is true that the reality would be more like an observational study. We need to acknowledge the limitation of our experiment in conclusion.

**Comment by dicook** [comment]
The work very specifically uses simulated data because we need to study a problem in controlled conditions. You are right, that data will pose more interesting challenges, and this can be in two directions. One, being that the lineup protocol will allow interesting and unexpected patterns in the residuals to be detected (see Buja et al and Wickham et al for examples). The other is that the current process for generating null data uses residual rotation and will likely maintain irrelevant quirks of the data in the null plots. These should not inadvertently allow the reader to detect the data plot based on quirks. 

We have addressed this criticism in the broader discussion of the use of residual plots and lineups for residual diagnostics added to Section XXX (see issue #11).

**Comment by dicook** [comment]
An observational study will hopefully be possible once a computer vision model is deployed that will allow analysts to upload their residuals for automated testing.

**Comment by TengMCing** [comment]
mixed linear model paper as an example of another residual structure
