### ISSUE TITLE
JCGS reviewer 1: (5) Lineup protocol is not very helpful for everyday use

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/lineup_residual_diagnostics#15]
Reviewer 1: "I use something like the lineup protocol in teaching to help students calibrate their assessment of diagnostic plots. But I doubt very much experienced analysts use them in practice. I do not think it is realistic or really that helpful to recommend their everyday use."

**Comment by TengMCing** [comment]
Glad to hear that the lineup protocol is taught in model diagnostics units.

Visual testing is a relatively new concept. It is true that experienced analysts don't use lineup protocol every day. But I believe they use diagnostic plots every day (I hope so). We have a discussion in the conclusion about the necessity of using lineup protocol to accurately read diagnostics plots. Perhaps our argument is not strong enough since we do not have any data or analysis supporting it. Existing studies may have relevant arguments that we can cite.

**Comment by dicook** [comment]
It can be argued that it is being used by practitioners based on download rates of the nullabor package, and applications articles that report usage. We agree that it is not widespread, and think that this is because it's a little unwieldy. The goal is to make it easier, particularly by employing an automated testing tool using computer vision, but this is not the subject of the current paper. 

We have added a sentence to Section XXX to make this clearer.
